### ISSUE TITLE
Transformers version

### ISSUE THREAD

**Issue by StrangeTcy** [polakowo/gpt2bot#7]
This is not an issues as such, it's a question: is there any particular reason for using transformers==2.3.0? At the time of the writing, the latest transformers library version was 3.0.2.
Does it introduce any bug, incompatibilities or anything else that is known to stop the scripts from working?

**Comment by polakowo** [comment]
The package was written when 2.3.0 was the latest transformers version. With 3.0.2 you can now rewrite decoder.py to only a dozen of lines. I was about to update gpt2bot but got stuck with another project. You're welcome to contribute :)

**Comment by StrangeTcy** [comment]
Oh, ok, thanks. I probably will contribute once I have anything useful _to_ contribute.
